openapi: 3.1.0
info:
  title: Agrar GPT API – BÜK3000 Soil (Shapefile)
  version: 1.0.1
servers:
  - url: https://agrar-gpt-api.onrender.com
paths:
  /soil:
    get:
      operationId: getSoilData
      summary: Get soil unit information from BÜK3000 shapefile
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: number
        - in: query
          name: lon
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Soil unit from BÜK3000 shapefile
          content:
            application/json:
              schema:
                type: object
                properties:
                  bodenname:
                    type: string
                    nullable: true
                  beschreibung:
                    type: string
                    nullable: true
                  leitboden:
                    type: string
                    nullable: true
                  begleitbo:
                    type: string
                    nullable: true
                  ausgangsmaterial:
                    type: string
                    nullable: true
                  quelle:
                    type: string
