openapi: 3.1.0
info:
  title: Agrar GPT API – mit Bodenbewertung
  version: 1.3.0
servers:
  - url: https://agrar-gpt-api.onrender.com
paths:
  /soil:
    get:
      operationId: getSoilData
      summary: Get soil quality data by coordinates
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: number
        - in: query
          name: lon
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Soil data response
          content:
            application/json:
              schema:
                type: object
                properties:
                  bodenart:
                    type: string
                  ackerzahl:
                    type: integer
                  gruenlandzahl:
                    type: integer
                  bonitaetsklasse:
                    type: string
                  bodenpunkte:
                    type: integer
