openapi: 3.1.0
info:
  title: Agrar GPT API – BGR Soil WMS (Debug-Version)
  version: 1.0.3
servers:
  - url: https://agrar-gpt-api.onrender.com
paths:
  /soil:
    get:
      operationId: getSoilData
      summary: Debug soil data via BGR WMS with HTML logging
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: number
        - in: query
          name: lon
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Soil data
          content:
            application/json:
              schema:
                type: object
                properties:
                  BEZEICHNUNG:
                    type: string
                    nullable: true
                  LEITBODEN:
                    type: string
                    nullable: true
                  AUSGANGSGESTEIN:
                    type: string
                    nullable: true
                  GLEICHHEIT:
                    type: string
                    nullable: true
                  quelle:
                    type: string
