openapi: 3.1.0
info:
  title: Agrar GPT API – Climate & Value
  version: 1.2.0
servers:
  - url: https://agrar-gpt-api.onrender.com
paths:
  /climate:
    get:
      operationId: getClimateData
      summary: Get climate forecast and trend data (Open-Meteo)
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: number
        - in: query
          name: lon
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Climate forecast and trend data
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature_avg:
                    type: number
                  temperature_min:
                    type: number
                  temperature_max:
                    type: number
                  precipitation_mm:
                    type: number
                  wind_speed_max:
                    type: number
                  sunshine_hours:
                    type: number
                  vegetation_days_estimate:
                    type: integer
                  trend:
                    type: object
                    properties:
                      10y_temp_rise:
                        type: number
                      10y_precip_change:
                        type: number
  /value:
    get:
      operationId: getLandValue
      summary: Get official land value by district name
      parameters:
        - in: query
          name: landkreis
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Land value data from Destatis GENESIS API
          content:
            application/json:
              schema:
                type: object
                properties:
                  landkreis:
                    type: string
                  preise_eur_ha:
                    type: object
                    additionalProperties:
                      type: number
