openapi: 3.1.0
info:
  title: Agrar GPT API – Echte Bodendaten
  version: 1.4.0
servers:
  - url: https://agrar-gpt-api.onrender.com
paths:
  /soil:
    get:
      operationId: getSoilData
      summary: Get real soil data from BGR WMS
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: number
        - in: query
          name: lon
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Soil data response
          content:
            application/json:
              schema:
                type: object
                properties:
                  bodenart:
                    type: string
                  textur:
                    type: string
                  bodenklasse:
                    type: string
                  ackerzahl:
                    type: integer
                  gruenlandzahl:
                    type: integer
                  bodenpunkte:
                    type: integer
        '400':
          description: Invalid coordinates
        '404':
          description: No data at this location
