openapi: 3.1.0
info:
  title: Agrar GPT API
  version: 1.1.0
servers:
  - url: https://agrar-gpt-api.onrender.com
paths:
  /climate:
    get:
      operationId: getClimateData
      summary: Get climate data by coordinates
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: number
        - in: query
          name: lon
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Climate data response
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature_avg:
                    type: number
                  precipitation_mm:
                    type: number
                  vegetation_period_days:
                    type: integer
                  trend:
                    type: object
                    properties:
                      10y_temp_rise:
                        type: number
                      10y_precip_change:
                        type: number
  /value:
    get:
      operationId: getLandValue
      summary: Get land value by district name or code
      parameters:
        - in: query
          name: landkreis
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Land value data
          content:
            application/json:
              schema:
                type: object
                properties:
                  landkreis:
                    type: string
                  preise_eur_ha:
                    type: object
                    additionalProperties:
                      type: number
