openapi: 3.1.0
info:
  title: Agrar GPT API
  version: "1.0"
paths:
  /soil:
    get:
      operationId: getSoilData
      summary: Liefert Bodendaten
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
        - name: lon
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Erfolgreiche Antwort
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    nullable: true
                  quelle:
                    type: string
                required:
                  - quelle
        '404':
          description: Keine Daten gefunden
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                required:
                  - detail
