openapi: "3.1.0"
info:
  title: Agrar GPT API
  version: "1.0.0"
servers:
  - url: https://agrar-gpt-api.onrender.com
    description: Deployment auf Render
paths:
  /soil:
    get:
      operationId: getSoilData
      summary: Abruf von Bodendaten auf Basis von Koordinaten
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
        - name: lon
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Erfolgreiche Antwort mit Bodendaten
          content:
            application/json:
              schema:
                type: object
                properties:
                  bodenname:
                    type: string
                    nullable: true
                  beschreibung:
                    type: string
                    nullable: true
                  leitboden:
                    type: string
                    nullable: true
                  begleitbo:
                    type: string
                    nullable: true
                  ausgangsmaterial:
                    type: string
                    nullable: true
                  quelle:
                    type: string
                    nullable: true
        '404':
          description: Keine Daten gefunden
